services:
  mt5:
    image: gmag11/metatrader5_vnc
    container_name: mt5
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    environment:
      - CUSTOM_USER=tepafril
      - PASSWORD=316619AAbbcc**!!
    depends_on:
      - postgres
    networks:
      - mt5_network
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tepafril
      POSTGRES_PASSWORD: 316619AAbbcc**!!
      POSTGRES_DB: mt5_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mt5_network

volumes:
  postgres_data:

networks:
  mt5_network:
    driver: bridge