version: '3'
services:
  mt5:
    image: gmag11/metatrader5_vnc
    container_name: mt5
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    environment:
      - CUSTOM_USER=<Choose a user>
      - PASSWORD=<Choose a secure password>
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: mt5_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<Choose a secure password>
      - POSTGRES_DB=mt5_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: