services:
  mt5:
    build:
      context: .
      dockerfile: Dockerfile.mt5
    image: gmag11/metatrader5_vnc
    container_name: mt5
    volumes:
      - ./config:/config
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 3000:3000
      - 8001:8001
      - 5432:5432
    environment:
      - CUSTOM_USER=tepafril
      - PASSWORD=316619AAbbcc**!!
      - POSTGRES_USER=tepafril
      - POSTGRES_PASSWORD=316619AAbbcc**!!
      - POSTGRES_DB=mt5_data
    restart: unless-stopped
    networks:
      - mt5_network

networks:
  mt5_network:
    driver: bridge

volumes:
  postgres_data:
